---
title: "HW2_visualization"
author: "KiseokLee"
date: "2022-04-03"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## HW2 Visualization

Researcher: **Kiseok Lee** \
Date: 4/3/22 \
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

```

## HW2 problem 3.
Now make a plot of $E[sub]$ as a function of $m$ for $n = 1000$.  Here is the main point 
$$  E[sub] = 6\alpha \Delta t = \boxed{-\dfrac{3}{4}\log (1 - \dfrac{4}{3}\dfrac{m}{n})} $$
```{r}
m <- seq(0, 3000/4, length.out = 10000)

E_sub <- -3/4 * log(1-( (4*m) / (3*1000) ))

plot(m, E_sub, col = "blue", lty = 1, pch = 19, lwd = 1, 
     ylab = "E[sub]", main = "Expected number of substitutions given the number of observed substitutions(m)")


```

## HW2 problem 4. Import data and match the smaple IDs to Pangea IDs.

```{r}
t_w1 <- openxlsx::read.xlsx("data/OM.CompanionTables.xlsx", sheet = "Table W1")
dim(t_w1) # 245
head(t_w1)
tail(t_w1)
colnames(t_w1)

df_w1 <- t_w1 %>% select("Sample.label.[TARA_station#_environmental-feature_size-fraction]", "PANGAEA.sample.identifier") %>% rename(Sample.label="Sample.label.[TARA_station#_environmental-feature_size-fraction]", PANGAEA.Sample.ID = "PANGAEA.sample.identifier")

dim(df_w1) # 243

t_w8 <- openxlsx::read.xlsx("data/OM.CompanionTables.xlsx", sheet = "Table W8")
dim(t_w8) # 245
head(t_w8)
tail(t_w8)
colnames(t_w8)
t_w8 <- t_w8[1:243, ]
# remove 2 rows at the bottom


# what is the 2 IDs that are not in W1?
intersect(df_w1$PANGAEA.Sample.ID, t_w8$PANGAEA.Sample.ID)
length(intersect(df_w1$PANGAEA.Sample.ID, t_w8$PANGAEA.Sample.ID))

setdiff(df_w1$PANGAEA.Sample.ID, t_w8$PANGAEA.Sample.ID)
setdiff(t_w8$PANGAEA.Sample.ID, df_w1$PANGAEA.Sample.ID) # remove 2 rows at the bottom

# Left join
df_w18 <- df_w1 %>% left_join(t_w8, by = c("PANGAEA.Sample.ID" = "PANGAEA.Sample.ID"))
dim(df_w18)
head(df_w18)
tail(df_w18)
colnames(df_w18)
length(unique(df_w18$PANGAEA.Sample.ID)) # 243

df_w18$Sample.label

openxlsx::write.xlsx(df_w18, "Sample.label_metadata.xlsx")
```








